/* 
 * Orbit API
 *
 * Please see the complete Orbit API documentation at [https://docs.orbit.love/reference](https://docs.orbit.love/reference).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Orbit.Api.Client;
using Orbit.Api.Model;

namespace Orbit.Api.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface INotesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get the member&#x27;s notes
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="page"> (optional)</param>
        /// <returns></returns>
        void WorkspaceSlugMembersMemberSlugNotesGet (string workspaceSlug, string memberSlug, string page = null);

        /// <summary>
        /// Get the member&#x27;s notes
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="page"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> WorkspaceSlugMembersMemberSlugNotesGetWithHttpInfo (string workspaceSlug, string memberSlug, string page = null);
        /// <summary>
        /// Update a note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns></returns>
        void WorkspaceSlugMembersMemberSlugNotesIdPut (string workspaceSlug, string memberSlug, string id, Note body = null);

        /// <summary>
        /// Update a note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> WorkspaceSlugMembersMemberSlugNotesIdPutWithHttpInfo (string workspaceSlug, string memberSlug, string id, Note body = null);
        /// <summary>
        /// Create a note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="body"> (optional)</param>
        /// <returns></returns>
        void WorkspaceSlugMembersMemberSlugNotesPost (string workspaceSlug, string memberSlug, Note body = null);

        /// <summary>
        /// Create a note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> WorkspaceSlugMembersMemberSlugNotesPostWithHttpInfo (string workspaceSlug, string memberSlug, Note body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get the member&#x27;s notes
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="page"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task WorkspaceSlugMembersMemberSlugNotesGetAsync (string workspaceSlug, string memberSlug, string page = null);

        /// <summary>
        /// Get the member&#x27;s notes
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="page"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> WorkspaceSlugMembersMemberSlugNotesGetAsyncWithHttpInfo (string workspaceSlug, string memberSlug, string page = null);
        /// <summary>
        /// Update a note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task WorkspaceSlugMembersMemberSlugNotesIdPutAsync (string workspaceSlug, string memberSlug, string id, Note body = null);

        /// <summary>
        /// Update a note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> WorkspaceSlugMembersMemberSlugNotesIdPutAsyncWithHttpInfo (string workspaceSlug, string memberSlug, string id, Note body = null);
        /// <summary>
        /// Create a note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task WorkspaceSlugMembersMemberSlugNotesPostAsync (string workspaceSlug, string memberSlug, Note body = null);

        /// <summary>
        /// Create a note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> WorkspaceSlugMembersMemberSlugNotesPostAsyncWithHttpInfo (string workspaceSlug, string memberSlug, Note body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class NotesApi : INotesApi
    {
        private Orbit.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="NotesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public NotesApi(String basePath)
        {
            this.Configuration = new Orbit.Api.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Orbit.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotesApi"/> class
        /// </summary>
        /// <returns></returns>
        public NotesApi()
        {
            this.Configuration = Orbit.Api.Client.Configuration.Default;

            ExceptionFactory = Orbit.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public NotesApi(Orbit.Api.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Orbit.Api.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Orbit.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Orbit.Api.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Orbit.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get the member&#x27;s notes 
        /// </summary>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="page"> (optional)</param>
        /// <returns></returns>
        public void WorkspaceSlugMembersMemberSlugNotesGet (string workspaceSlug, string memberSlug, string page = null)
        {
             WorkspaceSlugMembersMemberSlugNotesGetWithHttpInfo(workspaceSlug, memberSlug, page);
        }

        /// <summary>
        /// Get the member&#x27;s notes 
        /// </summary>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="page"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> WorkspaceSlugMembersMemberSlugNotesGetWithHttpInfo (string workspaceSlug, string memberSlug, string page = null)
        {
            // verify the required parameter 'workspaceSlug' is set
            if (workspaceSlug == null)
                throw new ApiException(400, "Missing required parameter 'workspaceSlug' when calling NotesApi->WorkspaceSlugMembersMemberSlugNotesGet");
            // verify the required parameter 'memberSlug' is set
            if (memberSlug == null)
                throw new ApiException(400, "Missing required parameter 'memberSlug' when calling NotesApi->WorkspaceSlugMembersMemberSlugNotesGet");

            var localVarPath = "./{workspace_slug}/members/{member_slug}/notes";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (workspaceSlug != null) localVarPathParams.Add("workspace_slug", this.Configuration.ApiClient.ParameterToString(workspaceSlug)); // path parameter
            if (memberSlug != null) localVarPathParams.Add("member_slug", this.Configuration.ApiClient.ParameterToString(memberSlug)); // path parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            // authentication (bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspaceSlugMembersMemberSlugNotesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Get the member&#x27;s notes 
        /// </summary>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="page"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task WorkspaceSlugMembersMemberSlugNotesGetAsync (string workspaceSlug, string memberSlug, string page = null)
        {
             await WorkspaceSlugMembersMemberSlugNotesGetAsyncWithHttpInfo(workspaceSlug, memberSlug, page);

        }

        /// <summary>
        /// Get the member&#x27;s notes 
        /// </summary>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="page"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> WorkspaceSlugMembersMemberSlugNotesGetAsyncWithHttpInfo (string workspaceSlug, string memberSlug, string page = null)
        {
            // verify the required parameter 'workspaceSlug' is set
            if (workspaceSlug == null)
                throw new ApiException(400, "Missing required parameter 'workspaceSlug' when calling NotesApi->WorkspaceSlugMembersMemberSlugNotesGet");
            // verify the required parameter 'memberSlug' is set
            if (memberSlug == null)
                throw new ApiException(400, "Missing required parameter 'memberSlug' when calling NotesApi->WorkspaceSlugMembersMemberSlugNotesGet");

            var localVarPath = "./{workspace_slug}/members/{member_slug}/notes";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (workspaceSlug != null) localVarPathParams.Add("workspace_slug", this.Configuration.ApiClient.ParameterToString(workspaceSlug)); // path parameter
            if (memberSlug != null) localVarPathParams.Add("member_slug", this.Configuration.ApiClient.ParameterToString(memberSlug)); // path parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            // authentication (bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspaceSlugMembersMemberSlugNotesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Update a note 
        /// </summary>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns></returns>
        public void WorkspaceSlugMembersMemberSlugNotesIdPut (string workspaceSlug, string memberSlug, string id, Note body = null)
        {
             WorkspaceSlugMembersMemberSlugNotesIdPutWithHttpInfo(workspaceSlug, memberSlug, id, body);
        }

        /// <summary>
        /// Update a note 
        /// </summary>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> WorkspaceSlugMembersMemberSlugNotesIdPutWithHttpInfo (string workspaceSlug, string memberSlug, string id, Note body = null)
        {
            // verify the required parameter 'workspaceSlug' is set
            if (workspaceSlug == null)
                throw new ApiException(400, "Missing required parameter 'workspaceSlug' when calling NotesApi->WorkspaceSlugMembersMemberSlugNotesIdPut");
            // verify the required parameter 'memberSlug' is set
            if (memberSlug == null)
                throw new ApiException(400, "Missing required parameter 'memberSlug' when calling NotesApi->WorkspaceSlugMembersMemberSlugNotesIdPut");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling NotesApi->WorkspaceSlugMembersMemberSlugNotesIdPut");

            var localVarPath = "./{workspace_slug}/members/{member_slug}/notes/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (workspaceSlug != null) localVarPathParams.Add("workspace_slug", this.Configuration.ApiClient.ParameterToString(workspaceSlug)); // path parameter
            if (memberSlug != null) localVarPathParams.Add("member_slug", this.Configuration.ApiClient.ParameterToString(memberSlug)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspaceSlugMembersMemberSlugNotesIdPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Update a note 
        /// </summary>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task WorkspaceSlugMembersMemberSlugNotesIdPutAsync (string workspaceSlug, string memberSlug, string id, Note body = null)
        {
             await WorkspaceSlugMembersMemberSlugNotesIdPutAsyncWithHttpInfo(workspaceSlug, memberSlug, id, body);

        }

        /// <summary>
        /// Update a note 
        /// </summary>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> WorkspaceSlugMembersMemberSlugNotesIdPutAsyncWithHttpInfo (string workspaceSlug, string memberSlug, string id, Note body = null)
        {
            // verify the required parameter 'workspaceSlug' is set
            if (workspaceSlug == null)
                throw new ApiException(400, "Missing required parameter 'workspaceSlug' when calling NotesApi->WorkspaceSlugMembersMemberSlugNotesIdPut");
            // verify the required parameter 'memberSlug' is set
            if (memberSlug == null)
                throw new ApiException(400, "Missing required parameter 'memberSlug' when calling NotesApi->WorkspaceSlugMembersMemberSlugNotesIdPut");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling NotesApi->WorkspaceSlugMembersMemberSlugNotesIdPut");

            var localVarPath = "./{workspace_slug}/members/{member_slug}/notes/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (workspaceSlug != null) localVarPathParams.Add("workspace_slug", this.Configuration.ApiClient.ParameterToString(workspaceSlug)); // path parameter
            if (memberSlug != null) localVarPathParams.Add("member_slug", this.Configuration.ApiClient.ParameterToString(memberSlug)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspaceSlugMembersMemberSlugNotesIdPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Create a note 
        /// </summary>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="body"> (optional)</param>
        /// <returns></returns>
        public void WorkspaceSlugMembersMemberSlugNotesPost (string workspaceSlug, string memberSlug, Note body = null)
        {
             WorkspaceSlugMembersMemberSlugNotesPostWithHttpInfo(workspaceSlug, memberSlug, body);
        }

        /// <summary>
        /// Create a note 
        /// </summary>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> WorkspaceSlugMembersMemberSlugNotesPostWithHttpInfo (string workspaceSlug, string memberSlug, Note body = null)
        {
            // verify the required parameter 'workspaceSlug' is set
            if (workspaceSlug == null)
                throw new ApiException(400, "Missing required parameter 'workspaceSlug' when calling NotesApi->WorkspaceSlugMembersMemberSlugNotesPost");
            // verify the required parameter 'memberSlug' is set
            if (memberSlug == null)
                throw new ApiException(400, "Missing required parameter 'memberSlug' when calling NotesApi->WorkspaceSlugMembersMemberSlugNotesPost");

            var localVarPath = "./{workspace_slug}/members/{member_slug}/notes";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (workspaceSlug != null) localVarPathParams.Add("workspace_slug", this.Configuration.ApiClient.ParameterToString(workspaceSlug)); // path parameter
            if (memberSlug != null) localVarPathParams.Add("member_slug", this.Configuration.ApiClient.ParameterToString(memberSlug)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspaceSlugMembersMemberSlugNotesPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Create a note 
        /// </summary>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task WorkspaceSlugMembersMemberSlugNotesPostAsync (string workspaceSlug, string memberSlug, Note body = null)
        {
             await WorkspaceSlugMembersMemberSlugNotesPostAsyncWithHttpInfo(workspaceSlug, memberSlug, body);

        }

        /// <summary>
        /// Create a note 
        /// </summary>
        /// <exception cref="Orbit.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceSlug"></param>
        /// <param name="memberSlug"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> WorkspaceSlugMembersMemberSlugNotesPostAsyncWithHttpInfo (string workspaceSlug, string memberSlug, Note body = null)
        {
            // verify the required parameter 'workspaceSlug' is set
            if (workspaceSlug == null)
                throw new ApiException(400, "Missing required parameter 'workspaceSlug' when calling NotesApi->WorkspaceSlugMembersMemberSlugNotesPost");
            // verify the required parameter 'memberSlug' is set
            if (memberSlug == null)
                throw new ApiException(400, "Missing required parameter 'memberSlug' when calling NotesApi->WorkspaceSlugMembersMemberSlugNotesPost");

            var localVarPath = "./{workspace_slug}/members/{member_slug}/notes";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (workspaceSlug != null) localVarPathParams.Add("workspace_slug", this.Configuration.ApiClient.ParameterToString(workspaceSlug)); // path parameter
            if (memberSlug != null) localVarPathParams.Add("member_slug", this.Configuration.ApiClient.ParameterToString(memberSlug)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspaceSlugMembersMemberSlugNotesPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                null);
        }

    }
}
