/* 
 * Orbit API
 *
 * Please see the complete Orbit API documentation at [https://docs.orbit.love/reference](https://docs.orbit.love/reference).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Orbit.Api.Client.SwaggerDateConverter;

namespace Orbit.Api.Model
{
    /// <summary>
    /// CustomOrPostActivity
    /// </summary>
    [DataContract]
        public partial class CustomOrPostActivity :  IEquatable<CustomOrPostActivity>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomOrPostActivity" /> class.
        /// </summary>
        public CustomOrPostActivity()
        {
        }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CustomOrPostActivity {\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CustomOrPostActivity);
        }

        /// <summary>
        /// Returns true if CustomOrPostActivity instances are equal
        /// </summary>
        /// <param name="input">Instance of CustomOrPostActivity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CustomOrPostActivity input)
        {
            if (input == null)
                return false;

            return false;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                return hashCode;
            }
        }
    }
}
