name: GitHub Actions Demo
on: [push]
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v2
      
    - name: Build and Test
      run: scripts/build.sh
    
    - name: Test Api Access
      run: scripts/run.sh
      