name: Orbit Sync
on:
  workflow_dispatch: {}
  schedule:
  - cron: '30 0 * * *' # run at 12:30 every day

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: dotnet build
    
    - name: Test Api Access
      run: scripts/run.sh sync
      env:
        ORBIT_API_TOKEN: ${{ secrets.ORBIT_API_TOKEN }}
        PCO_APPLICATION_ID: ${{ secrets.PCO_APPLICATION_ID }}
        PCO_SECRET: ${{ secrets.PCO_SECRET }}
        
    - uses: actions/upload-artifact@v2
      with:
        name: run-data
        path: |
          *.db
          *.log
          *.csv
          
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      if: always()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: |
          Orbit Sync Completed with: ${{ job.status }}
          
          ```
          ${{env.SYNC_SUMMARY}}
          ```
        SLACK_ICON: https://assets-global.website-files.com/6090f2cbfb550680d4288567/60916d2d77cab34ad9d7666f_Logo.svg
