name: Orbit Sync
on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Mode to run the sync in'
        required: true
        default: 'test'
  schedule:
  - cron: '30 0 * * *' # run at 12:30 every day

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: dotnet build
    
    - name: Test Api Access
      run: scripts/run.sh ${{ github.event.inputs.mode }}
      env:
        ORBIT_API_TOKEN: ${{ secrets.ORBIT_API_TOKEN }}
        PCO_APPLICATION_ID: ${{ secrets.PCO_APPLICATION_ID }}
        PCO_SECRET: ${{ secrets.PCO_SECRET }}
